server:
  port: 8081
  servlet:
    session:
      cookie:
        name: OAUTH2SESSION


spring:
  application:
    name: user-server
  mvc:
    throw-exception-if-no-handler-found: true # 捕获404错误
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://localhost:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,页面会显示主机名
    preferIpAddress: true  # 访问路径可以显示IP地址
mengxuegu:
  cloud:
    cloudClientDetail:
      clientId: mengxuegu-pc
      clientSecret: mengxuegu-secret

#security:
#  oauth2:
#    client:
#      pre-established-redirect-uri: http://localhost:8090/auth/callback
#      client-id: mengxuegu-pc
#      client-secret: mengxuegu-secret
#      user-authorization-uri: http://localhost:8090/auth/oauth/authorize
#      access-token-uri: http://localhost:8090/auth/oauth/token