

menggxuegu:
  cloud:
    clientId: mengxuegu-pc
    clientSecret: mengxuegu-secret
server:
  port: 8081
spring:
  application:
    name: user-server
  mvc:
    throw-exception-if-no-handler-found: true # 捕获404错误
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://localhost:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,页面会显示主机名
    preferIpAddress: true  # 访问路径可以显示IP地址